name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push images
        run: |
          docker compose push
  
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set up Kubernetes context
        run: |
          echo "${{ secrets.KUBE_CA_CERT }}" > ca.crt  # сертификат удостоверяющего центра
          kubectl config set-cluster yc-managed-k8s-catlbe79o7tovp5cd5k0 --server=https://130.193.45.63 --certificate-authority=ca.crt
          kubectl config set-credentials yc-managed-k8s-catlbe79o7tovp5cd5k0 --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context yc-dipslab4 --cluster=yc-managed-k8s-catlbe79o7tovp5cd5k0 --user=yc-managed-k8s-catlbe79o7tovp5cd5k0
          kubectl config use-context yc-dipslab4

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/

      - name: Verify deployment
        run: |
          kubectl get pods
          kubectl get services
          
  test:
    name: Test
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run API Tests
      uses: matt-ball/newman-action@master
      with:
        collection: v2/postman/collection.json
        environment: v2/postman/environment.json
        delayRequest: 100
        reporters: '[ "cli" ]'

    - uses: education/autograding@v1
      id: autograder
      continue-on-error: true

    - name: Github auto grader mark
      uses: Romanow/google-sheet-autograder-marker@v1.0
      with:
        google_token: ${{secrets.GOOGLE_API_KEY}}
        sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
        homework_number: 4
        user_column: 'D'
        column_offset: 'F'
        mark: "'+"